
with base as (

    select * 
    from {{ source('salesforce', 'user') }}
),

final as (
    
    select 
        id,
        username,
        last_name,
        first_name,
        middle_name,
        suffix,
        name,
        company_name,
        division,
        department,
        title,
        street,
        city,
        state,
        postal_code,
        country,
        state_code,
        country_code,
        latitude,
        longitude,
        geocode_accuracy,
        email,
        email_preferences_auto_bcc,
        email_preferences_auto_bcc_stay_in_touch,
        email_preferences_stay_in_touch_reminder,
        sender_email,
        sender_name,
        signature,
        stay_in_touch_subject,
        stay_in_touch_signature,
        stay_in_touch_note,
        phone,
        fax,
        mobile_phone,
        alias,
        community_nickname,
        badge_text,
        is_active,
        time_zone_sid_key,
        user_role_id,
        locale_sid_key,
        receives_info_emails,
        receives_admin_info_emails,
        email_encoding_key,
        profile_id,
        user_type,
        language_locale_key,
        employee_number,
        delegated_approver_id,
        manager_id,
        cast(last_login_date as {{ dbt.type_timestamp() }}) as last_login_date,
        cast(created_date as {{ dbt.type_timestamp() }}) as created_date,
        created_by_id,
        cast(last_modified_date as {{ dbt.type_timestamp() }}) as last_modified_date,
        last_modified_by_id,
        system_modstamp,
        cast(offline_trial_expiration_date as {{ dbt.type_timestamp() }}) as offline_trial_expiration_date,
        cast(offline_pda_trial_expiration_date as {{ dbt.type_timestamp() }}) as offline_pda_trial_expiration_date,
        user_permissions_marketing_user,
        user_permissions_offline_user,
        user_permissions_avantgo_user,
        user_permissions_call_center_auto_login,
        user_permissions_sfcontent_user,
        user_permissions_knowledge_user,
        user_permissions_interaction_user,
        user_permissions_support_user,
        user_permissions_live_agent_user,
        forecast_enabled,
        user_preferences_activity_reminders_popup,
        user_preferences_event_reminders_checkbox_default,
        user_preferences_task_reminders_checkbox_default,
        user_preferences_reminder_sound_off,
        user_preferences_disable_all_feeds_email,
        user_preferences_disable_followers_email,
        user_preferences_disable_profile_post_email,
        user_preferences_disable_change_comment_email,
        user_preferences_disable_later_comment_email,
        user_preferences_dis_prof_post_comment_email,
        user_preferences_apex_pages_developer_mode,
        user_preferences_receive_no_notifications_as_approver,
        user_preferences_receive_notifications_as_delegated_approver,
        user_preferences_hide_csnget_chatter_mobile_task,
        user_preferences_disable_mentions_post_email,
        user_preferences_dis_mentions_comment_email,
        user_preferences_hide_csndesktop_task,
        user_preferences_hide_chatter_onboarding_splash,
        user_preferences_hide_second_chatter_onboarding_splash,
        user_preferences_dis_comment_after_like_email,
        user_preferences_disable_like_email,
        user_preferences_sort_feed_by_comment,
        user_preferences_disable_message_email,
        user_preferences_disable_bookmark_email,
        user_preferences_disable_share_post_email,
        user_preferences_enable_auto_sub_for_feeds,
        user_preferences_disable_file_share_notifications_for_api,
        user_preferences_show_title_to_external_users,
        user_preferences_show_manager_to_external_users,
        user_preferences_show_email_to_external_users,
        user_preferences_show_work_phone_to_external_users,
        user_preferences_show_mobile_phone_to_external_users,
        user_preferences_show_fax_to_external_users,
        user_preferences_show_street_address_to_external_users,
        user_preferences_show_city_to_external_users,
        user_preferences_show_state_to_external_users,
        user_preferences_show_postal_code_to_external_users,
        user_preferences_show_country_to_external_users,
        user_preferences_show_profile_pic_to_guest_users,
        user_preferences_show_title_to_guest_users,
        user_preferences_show_city_to_guest_users,
        user_preferences_show_state_to_guest_users,
        user_preferences_show_postal_code_to_guest_users,
        user_preferences_show_country_to_guest_users,
        user_preferences_show_forecasting_change_signals,
        user_preferences_hide_s_1_browser_ui,
        user_preferences_disable_endorsement_email,
        user_preferences_path_assistant_collapsed,
        user_preferences_cache_diagnostics,
        user_preferences_show_email_to_guest_users,
        user_preferences_show_manager_to_guest_users,
        user_preferences_show_work_phone_to_guest_users,
        user_preferences_show_mobile_phone_to_guest_users,
        user_preferences_show_fax_to_guest_users,
        user_preferences_show_street_address_to_guest_users,
        user_preferences_lightning_experience_preferred,
        user_preferences_hide_end_user_onboarding_assistant_modal,
        user_preferences_hide_lightning_migration_modal,
        user_preferences_hide_sfx_welcome_mat,
        user_preferences_hide_bigger_photo_callout,
        user_preferences_global_nav_bar_wtshown,
        user_preferences_global_nav_grid_menu_wtshown,
        user_preferences_create_lexapps_wtshown,
        user_preferences_favorites_wtshown,
        user_preferences_record_home_section_collapse_wtshown,
        user_preferences_record_home_reserved_wtshown,
        user_preferences_favorites_show_top_favorites,
        user_preferences_exclude_mail_app_attachments,
        user_preferences_suppress_task_sfxreminders,
        user_preferences_suppress_event_sfxreminders,
        user_preferences_preview_custom_theme,
        user_preferences_has_celebration_badge,
        user_preferences_user_debug_mode_pref,
        user_preferences_srhoverride_activities,
        user_preferences_new_lightning_report_run_page_enabled,
        user_preferences_reverse_open_activities_view,
        user_preferences_has_sent_warning_email,
        user_preferences_has_sent_warning_email_238,
        user_preferences_has_sent_warning_email_240,
        user_preferences_hide_browse_product_redirect_confirmation,
        user_preferences_hide_online_sales_app_welcome_mat,
        contact_id,
        account_id,
        call_center_id,
        extension,
        portal_role,
        is_portal_enabled,
        federation_identifier,
        about_me,
        full_photo_url,
        small_photo_url,
        is_ext_indicator_visible,
        out_of_office_message,
        medium_photo_url,
        digest_frequency,
        default_group_notification_frequency,
        cast(last_viewed_date as {{ dbt.type_timestamp() }}) as last_viewed_date,
        cast(last_referenced_date as {{ dbt.type_timestamp() }}) as last_referenced_date,
        banner_photo_url,
        small_banner_photo_url,
        medium_banner_photo_url,
        is_profile_photo_active,
        individual_id,
        _fivetran_deleted,
        _fivetran_synced,
        echosign_dev_1_echo_sign_email_verified_c,
        echosign_dev_1_echo_sign_allow_delegated_sending_c
                
    from base
)

select *
from final