{{
    config(
        tags=["piperider"]
    )
}}
with base as (

    select * 
    from {{ source('salesforce', 'case') }}
),

final as (
    
    select 
        cast(_fivetran_synced as {{ dbt.type_timestamp() }}) as _fivetran_synced,
        id as case_id,
        is_deleted,
        master_record_id,
        case_number,
        contact_id,
        account_id,
        parent_id,
        supplied_name,
        supplied_email,
        supplied_phone,
        supplied_company,
        type,
        record_type_id,
        status,
        reason,
        origin,
        language,
        subject,
        priority,
        description as case_description,
        is_closed,
        cast(closed_date as {{ dbt.type_timestamp() }}) as closed_date,
        is_escalated,
        owner_id,
        cast(created_date as {{ dbt.type_timestamp() }}) as created_date,
        created_by_id,
        cast(last_modified_date as {{ dbt.type_timestamp() }}) as last_modified_date,
        last_modified_by_id,
        system_modstamp,
        contact_phone,
        contact_mobile,
        contact_email,
        contact_fax,
        comments,
        cast(last_viewed_date as {{ dbt.type_timestamp() }}) as last_viewed_date,
        cast(last_referenced_date as {{ dbt.type_timestamp() }}) as last_referenced_date,
        sub_category_c,
        sub_sub_category_c,
        pdb_reference_c,
        _fivetran_deleted,
        workspace_id_c,
        work_around_available_c,
        clone_case_c,
        digital_certificate_4_middle_name_c,
        asset_id,
        digital_certificate_1_email_c,
        settlement_time_c,
        internal_status_c,
        digital_certificate_6_last_name_c,
        digital_certificate_7_last_name_c,
        digital_certificate_8_last_name_c,
        direct_debit_bank_account_number_c,
        digital_certificate_5_email_c,
        resolved_email_sent_c,
        payment_authoriser_3_office_title_c,
        urgency_c,
        payment_authoriser_4_office_title_c,
        call_notes_c,
        integrated_service_partner_reference_c,
        jira_ticket_description_c,
        digital_certificate_8_email_c,
        assignment_group_c,
        digital_certificate_6_middle_name_c,
        digital_certificate_5_last_name_c,
        digital_certificate_4_last_name_c,
        digital_certificate_3_last_name_c,
        cause_c,
        digital_certificate_1_last_name_c,
        digital_certificate_2_last_name_c,
        digital_certificate_2_middle_name_c,
        trust_account_name_c,
        payment_authoriser_5_name_c,
        close_on_create_c,
        in_flight_transaction_c,
        settlement_time_2_c,
        digital_certificate_7_middle_name_c,
        direct_debit_bsb_c,
        not_a_new_registration_c,
        transaction_jurisdiction_c,
        number_of_impacted_users_c,
        digital_certificate_4_email_c,
        digital_certificate_1_middle_name_c,
        build_number_c,
        validation_officer_c,
        digital_certificate_1_name_c,
        trust_financial_instiution_name_c,
        digital_certificate_8_middle_name_c,
        settlement_date_c,
        digital_certificate_7_email_c,
        email_received_more_than_3_days_c,
        einstein_article_field_c,
        direct_debit_account_name_c,
        payment_authoriser_2_name_c,
        trust_account_number_c,
        digital_certificate_5_name_c,
        source_id,
        planned_release_date_c,
        number_of_messages_received_c,
        reason_for_contact_for_customer_email_c,
        service_now_reference_c,
        is_this_a_new_registration_c,
        date_survey_last_sent_c,
        genesys_interaction_id_c,
        severity_c,
        settlement_in_the_next_10_days_c,
        identified_internally_c,
        case_cannot_be_reopened_c,
        jurisdiction_c,
        sub_manager_c,
        change_code_required_c,
        digital_certificate_5_middle_name_c,
        payment_authoriser_5_office_title_c,
        digital_certificate_3_email_c,
        jira_reference_c,
        related_case_c,
        digital_certificate_3_middle_name_c,
        first_call_resolution_c,
        digital_certificate_2_name_c,
        transaction_type_c,
        impact_c,
        child_case_auto_email_c,
        integrated_service_partner_c,
        customer_progress_c,
        digital_certificate_8_name_c,
        digital_certificate_6_name_c,
        reference_number_c,
        resolution_c,
        payment_authoriser_2_office_title_c,
        digital_certificate_4_name_c,
        payment_authoriser_1_name_c,
        update_upon_case_comments_c,
        existing_abn_c,
        date_contact_last_surveyed_c,
        number_of_messages_sent_c,
        digital_certificate_expiry_date_c,
        payment_authoriser_3_name_c,
        payment_authoriser_4_name_c,
        new_registration_c,
        business_hours_id,
        payment_authoriser_1_office_title_c,
        digital_certificate_2_email_c,
        legacy_id_c,
        integrated_service_partner_2_c,
        digital_certificate_6_email_c,
        is_closed_on_create,
        mortgage_reference_id_c,
        additional_detail_for_customer_email_c,
        trust_bsb_c,
        automation_date_time_c,
        subscription_c,
        case_label_c,
        direct_debti_financial_inst_name_c,
        fi_customer_number_c,
        configuration_item_c,
        digital_certificate_7_name_c,
        case_resolution_c,
        case_reopened_c,
        lodgement_status_c,
        digital_certificate_3_name_c,
        resolution_notes_for_customer_email_c
        
    from base
)

select *
from final
where not coalesce(is_deleted, false)