with base as (

    select *
    from {{ source('salesforce', 'account') }}
), 

final as (

    select
         id,
         is_deleted,
         master_record_id,
         name,
         last_name,
         first_name,
         salutation,
         middle_name,
         suffix,
         type,
         record_type_id,
         parent_id,
         billing_street,
         billing_city,
         billing_state,
         billing_postal_code,
         billing_country,
         billing_state_code,
         billing_country_code,
         billing_latitude,
         billing_longitude,
         billing_geocode_accuracy,
         shipping_street,
         shipping_city,
         shipping_state,
         shipping_postal_code,
         shipping_country,
         shipping_state_code,
         shipping_country_code,
         shipping_latitude,
         shipping_longitude,
         shipping_geocode_accuracy,
         phone,
         website,
         photo_url,
         industry,
         number_of_employees,
         description,
         owner_id,
         cast(created_date as {{ dbt.type_timestamp() }}) as created_date,
         created_by_id,
         cast(last_modified_date as {{ dbt.type_timestamp() }}) as last_modified_date,
         last_modified_by_id,
         system_modstamp,
         cast(last_activity_date as {{ dbt.type_timestamp() }}) as last_activity_date,
         cast(last_viewed_date as {{ dbt.type_timestamp() }}) as last_viewed_date,
         cast(last_referenced_date as {{ dbt.type_timestamp() }}) as last_referenced_date,
         is_customer_portal,
         person_contact_id,
         is_person_account,
         person_mailing_street,
         person_mailing_city,
         person_mailing_state,
         person_mailing_postal_code,
         person_mailing_country,
         person_mailing_state_code,
         person_mailing_country_code,
         person_mailing_latitude,
         person_mailing_longitude,
         person_mailing_geocode_accuracy,
         person_mobile_phone,
         person_email,
         person_title,
         person_department,
         cast(person_last_curequest_date as {{ dbt.type_timestamp() }}) as person_last_curequest_date,
         cast(person_last_cuupdate_date as {{ dbt.type_timestamp() }}) as person_last_cuupdate_date,
         person_email_bounced_reason,
         cast(person_email_bounced_date as {{ dbt.type_timestamp() }}) as person_email_bounced_date,
         person_individual_id,
         jigsaw,
         jigsaw_company_id,
         account_source,
         sic_desc,
         exchange_subscriber_id_pc,
         _fivetran_deleted,
         _fivetran_synced,
         cast(ps_smssubscription_updated_pc as {{ dbt.type_timestamp() }}) as ps_smssubscription_updated_pc,
         ps_operational_2_c,
         remortgage_volume_estimate_c,
         ps_pexacertified_status_pc,
         ps_strategic_2_c,
         ps_alcoholic_preferences_pc,
         ps_information_broker_c,
         ps_industry_market_share_c,
         ps_method_pc,
         pexa_payment_authorisers_pc,
         ps_customer_segment_level_2_c,
         communication_notifications_pc,
         ps_entity_type_c,
         ps_status_c,
         fax,
         ps_customer_status_c,
         ps_account_plan_quip_document_url_c,
         ps_outage_notifications_pc,
         requires_additional_digital_certificate_pc,
         cast(ps_pexacertified_date_pc as {{ dbt.type_timestamp() }}) as ps_pexacertified_date_pc,
         ps_industry_partner_type_other_c,
         ps_phone_numbers_las_washed_results_pc,
         finance_contact_pc,
         sales_purchase_volume_estimate_c,
         pexa_payment_authorisers_1_pc,
         ps_offer_opt_out_pc,
         ps_pexamarket_share_c,
         ps_reporting_manager_pc,
         how_will_the_partnership_execute_the_ag_c,
         person_assistant_phone,
         secret_question_2_pc,
         ps_quip_folder_url_c,
         ps_registration_status_pc,
         current_contract_rate_c,
         person_other_city,
         cast(ps_activation_date_c as {{ dbt.type_timestamp() }}) as ps_activation_date_c,
         public_contact_pc,
         ps_sizeof_loan_book_c,
         industry_engagement_c,
         ps_relationship_status_pc,
         contact_frequency_pc,
         ps_ficategory_c,
         ps_channel_c,
         ps_asxreference_code_c,
         ps_industry_partner_type_c,
         ps_events_pc,
         primary_subscriber_manager_pc,
         ps_strategic_3_c,
         ps_operational_3_c,
         ticker_symbol,
         ps_abn_c,
         cast(ps_dateof_voi_pc as {{ dbt.type_timestamp() }}) as ps_dateof_voi_pc,
         person_other_phone,
         person_other_longitude,
         ps_organisation_pc,
         role_pc,
         trust_account_owners_pc,
         ps_smsopt_out_pc,
         exchange_last_login_pc,
         ps_legal_entity_name_c,
         disc_profile_pc,
         ps_institution_type_c,
         ps_external_id_pc,
         ps_pms_c,
         survey_opt_out_pc,
         person_other_country_code,
         ps_direct_reports_pc,
         ps_engagement_c,
         cmt_member_c,
         send_fx_rego_c,
         financial_institution_type_c,
         behavioural_segment_c,
         ps_symposiums_c,
         authorised_signatory_pc,
         contact_exchange_access_pc,
         ps_best_practice_groups_c,
         ps_linked_in_pc,
         ps_information_evenings_c,
         secret_question_2_answer_pc,
         person_lead_source,
         site,
         ps_business_unit_area_pc,
         ps_other_indicators_c,
         ownership,
         ps_panel_lawyer_c,
         person_assistant_name,
         ps_what_they_like_pc,
         contacts_status_pc,
         ps_external_documents_quip_document_url_c,
         ps_same_as_entity_address_pc,
         person_other_postal_code,
         event_participation_c,
         ps_awards_won_c,
         rating,
         person_other_country,
         how_many_property_transactions_per_month_c,
         ps_voicomplete_pc,
         ps_dietary_requirements_pc,
         ps_customer_segment_level_0_c,
         ps_business_unit_name_c,
         secret_question_1_pc,
         ps_secondary_email_pc,
         cast(date_last_survey_sent_pc as {{ dbt.type_timestamp() }}) as date_last_survey_sent_pc,
         ps_system_bypass_validation_datetime_c,
         ps_external_id_c,
         ps_terms_accepted_date_pc,
         capacity_for_signing_pc,
         ps_overall_healthof_account_c,
         subscriber_manager_pc,
         ps_offer_subscription_updated_pc,
         person_other_state_code,
         ps_email_subscription_updated_pc,
         ps_acn_c,
         panel_details_c,
         preferred_name_pc,
         ps_reoccuring_meetings_pc,
         subscriber_role_pc,
         ps_trusteeofa_trust_c,
         ps_business_phone_wash_results_pc,
         ps_terms_conditions_version_pc,
         ps_financial_year_c,
         ps_focusand_structureof_business_c,
         person_other_state,
         annual_revenue,
         person_has_opted_out_of_fax,
         account_number,
         ps_operational_1_c,
         ps_pmsother_c,
         ps_consumer_id_pc,
         ps_strategic_1_c,
         person_other_latitude,
         primary_signatory_pc,
         ps_primary_sourceof_business_c,
         sic,
         ps_pexacertified_status_c,
         competitor_c,
         secret_question_1_answer_pc,
         subscriber_manager_c,
         person_do_not_call,
         ps_customer_segment_level_1_c,
         ps_voiprovider_pc,
         contact_frequency_c,
         person_has_opted_out_of_email,
         what_type_is_your_trustee_c,
         ps_pexacertified_date_c,
         pexa_shareholder_c,
         subscriber_id_pc,
         person_home_phone,
         ps_mobile_phone_wash_results_pc,
         person_other_street,
         company_number_uk_c,
         person_other_geocode_accuracy,
         ps_pexadivision_pc,
         how_will_the_company_execute_agreements_c,
         ps_peopleinvolvedin_property_c,
         ps_non_alcoholic_preferences_pc,
         ps_information_broker_other_c,
         other_organisation_type_c,
         contract_status_c,
         cast(ps_registration_date_pc as {{ dbt.type_timestamp() }}) as ps_registration_date_pc,
         ps_likelihood_c,
         engagement_preference_c,
         ps_bio_pc,
         ps_account_management_segment_c,
         ps_survey_participation_pc,
         cast(person_birthdate as {{ dbt.type_timestamp() }}) as person_birthdate,
         ps_communication_type_pc,
         pexa_client_gift_pc
        
    from base
)

select *
from final
where not coalesce(is_deleted, false)
