{{
    config(
        tags=["piperider"]
    )
}}
with base as (

    select * 
    from {{ source('salesforce', 'contact') }}
),

final as (
    
    select 
        cast(_fivetran_synced as {{ dbt.type_timestamp() }}) as _fivetran_synced,
        id as contact_id,
        is_deleted,
        master_record_id,
        account_id,
        is_person_account,
        last_name,
        first_name,
        salutation,
        middle_name,
        suffix,
        name as contact_name,
        mailing_street,
        mailing_city,
        mailing_state,
        mailing_postal_code,
        mailing_country,
        mailing_state_code,
        mailing_country_code,
        mailing_latitude,
        mailing_longitude,
        mailing_geocode_accuracy,
        phone,
        fax,
        mobile_phone,
        reports_to_id,
        email,
        title,
        department,
        owner_id,
        created_date,
        created_by_id,
        last_modified_date,
        last_modified_by_id,
        system_modstamp,
        cast(last_activity_date as {{ dbt.type_timestamp() }}) as last_activity_date,
        last_curequest_date,
        last_cuupdate_date,
        cast(last_viewed_date as {{ dbt.type_timestamp() }}) as last_viewed_date,
        last_referenced_date,
        email_bounced_reason,
        email_bounced_date,
        is_email_bounced,
        photo_url,
        jigsaw,
        jigsaw_contact_id,
        individual_id,
        exchange_subscriber_id_c,
        _fivetran_deleted,
        pexa_client_gift_c,
        birthdate,
        secret_question_1_c,
        lead_source,
        ps_smssubscription_updated_c,
        primary_subscriber_manager_c,
        ps_voiprovider_c,
        role_c,
        ps_offer_subscription_updated_c,
        other_latitude,
        ps_what_they_like_c,
        trust_account_owners_c,
        communication_notifications_c,
        finance_contact_c,
        ps_bio_c,
        authorised_signatory_c,
        capacity_for_signing_c,
        ps_external_id_c,
        other_street,
        ps_organisation_c,
        other_city,
        ps_communication_type_c,
        home_phone,
        subscriber_id_c,
        ps_survey_participation_c,
        ps_linked_in_c,
        ps_relationship_status_c,
        ps_alcoholic_preferences_c,
        other_geocode_accuracy,
        preferred_name_c,
        other_state_code,
        secret_question_2_answer_c,
        ps_pexadivision_c,
        other_country,
        assistant_phone,
        ps_consumer_id_c,
        ps_non_alcoholic_preferences_c,
        ps_mobile_phone_wash_results_c,
        ps_phone_numbers_las_washed_results_c,
        secret_question_2_c,
        has_opted_out_of_fax,
        ps_email_subscription_updated_c,
        ps_method_c,
        ps_same_as_entity_address_c,
        subscriber_role_c,
        description as contact_description,
        ps_reoccuring_meetings_c,
        requires_additional_digital_certificate_c,
        ps_pexacertified_status_c,
        pexa_payment_authorisers_1_c,
        ps_reporting_manager_c,
        subscriber_manager_c,
        disc_profile_c,
        assistant_name,
        ps_secondary_email_c,
        contact_frequency_c,
        ps_voicomplete_c,
        ps_direct_reports_c,
        ps_pexacertified_date_c,
        survey_opt_out_c,
        secret_question_1_answer_c,
        ps_outage_notifications_c,
        ps_business_unit_area_c,
        ps_dietary_requirements_c,
        pexa_payment_authorisers_c,
        primary_signatory_c,
        ps_offer_opt_out_c,
        exchange_last_login_c,
        other_state,
        ps_business_phone_wash_results_c,
        ps_registration_status_c,
        other_phone,
        contact_exchange_access_c,
        contacts_status_c,
        ps_terms_conditions_version_c,
        other_country_code,
        other_postal_code,
        ps_registration_date_c,
        ps_terms_accepted_date_c,
        ps_smsopt_out_c,
        ps_dateof_voi_c,
        public_contact_c,
        other_longitude,
        ps_events_c,
        date_last_survey_sent_c,
        do_not_call,
        has_opted_out_of_email
        
    from base
)

select *
from final
where not coalesce(is_deleted, false)