
with base as (

    select * 
    from {{ ref('stg_salesforce_case') }}
),

final as (
    
    select 
    case_id AS case_id,
    account_id AS case_accountid,
    assignment_group_c AS case_assignment_group,
    build_number_c AS case_build_number,
    call_notes_c AS case_call_notes,
    case_label_c AS case_case_label,
    --case_owner_name_c AS case_case_owner_name,
    case_reopened_c AS case_case_reopened,
    case_resolution_c AS case_case_resolution,
    case_cannot_be_reopened_c AS case_case_cannot_be_reopened,
    cause_c AS case_cause,
    change_code_required_c AS case_change_code_required,
    created_date, 
    last_modified_date, 
    clone_case_c AS case_clone_case,
    close_on_create_c AS case_close_on_create,
    closed_date AS case_closeddate,
    comments AS case_comments,
    case_number, 
    subject, 
    contact_id AS case_contactid,
    date_contact_last_surveyed_c AS case_date_contact_last_surveyed,
    case_description AS case_description,
    digital_certificate_1_email_c AS case_digital_certificate_1_email,
    digital_certificate_1_last_name_c AS case_digital_certificate_1_last_name,
    digital_certificate_1_middle_name_c AS case_digital_certificate_1_middle_name,
    digital_certificate_1_name_c AS case_digital_certificate_1_name,
    digital_certificate_2_email_c AS case_digital_certificate_2_email,
    digital_certificate_2_last_name_c AS case_digital_certificate_2_last_name,
    digital_certificate_2_middle_name_c AS case_digital_certificate_2_middle_name,
    digital_certificate_2_name_c AS case_digital_certificate_2_name,
    digital_certificate_3_email_c AS case_digital_certificate_3_email,
    digital_certificate_3_last_name_c AS case_digital_certificate_3_last_name,
    digital_certificate_3_middle_name_c AS case_digital_certificate_3_middle_name,
    digital_certificate_3_name_c AS case_digital_certificate_3_name,
    digital_certificate_4_email_c AS case_digital_certificate_4_email,
    digital_certificate_4_last_name_c AS case_digital_certificate_4_last_name,
    digital_certificate_4_middle_name_c AS case_digital_certificate_4_middle_name,
    digital_certificate_4_name_c AS case_digital_certificate_4_name,
    digital_certificate_5_email_c AS case_digital_certificate_5_email,
    digital_certificate_5_last_name_c AS case_digital_certificate_5_last_name,
    digital_certificate_5_middle_name_c AS case_digital_certificate_5_middle_name,
    digital_certificate_5_name_c AS case_digital_certificate_5_name,
    digital_certificate_6_email_c AS case_digital_certificate_6_email,
    digital_certificate_6_last_name_c AS case_digital_certificate_6_last_name,
    digital_certificate_6_middle_name_c AS case_digital_certificate_6_middle_name,
    digital_certificate_6_name_c AS case_digital_certificate_6_name,
    digital_certificate_7_email_c AS case_digital_certificate_7_email,
    digital_certificate_7_last_name_c AS case_digital_certificate_7_last_name,
    digital_certificate_7_middle_name_c AS case_digital_certificate_7_middle_name,
    digital_certificate_7_name_c AS case_digital_certificate_7_name,
    digital_certificate_8_email_c AS case_digital_certificate_8_email,
    digital_certificate_8_last_name_c AS case_digital_certificate_8_last_name,
    digital_certificate_8_middle_name_c AS case_digital_certificate_8_middle_name,
    digital_certificate_8_name_c AS case_digital_certificate_8_name,
    digital_certificate_expiry_date_c AS case_digital_certificate_expiry_date,
    --escalatethiscase_c AS case_escalatethiscase,
    first_call_resolution_c AS case_first_call_resolution,
    genesys_interaction_id_c AS case_genesys_interaction_id,
    identified_internally_c AS case_identifiedinternally,
    impact_c AS case_impact,
    in_flight_transaction_c AS case_in_flight_transaction,
    --incident_c AS case_incident,
    integrated_service_partner_2_c AS case_integrated_service_partner2,
    integrated_service_partner_reference_c AS case_integrated_service_partner_reference,
    integrated_service_partner_c AS case_integrated_service_partner,
    internal_status_c AS case_internal_status,
    is_closed, 
    is_closed_on_create AS case_isclosedoncreate,
    is_deleted, 
    is_escalated AS case_isescalated,
    is_this_a_new_registration_c AS case_is_this_a_new_registration,
    jira_reference_c AS case_jira_reference,
    jira_ticket_description_c AS case_jira_ticket_description,
    jurisdiction_c AS case_jurisdiction,
    legacy_id_c AS case_legacy_id,
    --legal_entity_name_c AS case_legal_entity_name,
    lodgement_status_c AS case_lodgement_status,
    new_registration_c AS case_new_registration,
    number_of_impacted_users_c AS case_numberofimpactedusers,
    number_of_messages_received_c AS case_number_of_messages_received,
    number_of_messages_sent_c AS case_number_of_messages_sent,
    origin AS case_origin,
    owner_id AS case_ownerid,
    pdb_reference_c AS case_pdb_reference,
    parent_id AS case_parentid,
    --parent_jira_reference_c AS case_parent_jira_reference,
    planned_release_date_c AS case_planned_release_date,
    priority AS case_priority,
    reason AS case_reason,
    reference_number_c AS case_reference_number,
    related_case_c AS case_related_case,
    resolution_c AS case_resolution,
    resolved_email_sent_c AS case_resolved_email_sent,
    --sf18_case_id_c AS case_sf18_case_id,
    --srp_due_date_c AS case_srp_due_date,
    --srp_invitationid_c AS case_srp_invitationid,
    --srp_response_c AS case_srp_response,
   -- srp_review_outcome_c AS case_srp_review_outcome,
    --srp_survey_invite_c AS case_srp_survey_invite,
    service_now_reference_c AS case_service_now_reference,
    settlement_date_c AS case_settlement_date,
    settlement_time_2_c AS case_settlement_time2,
    settlement_time_c AS case_settlement_time,
    severity_c AS case_severity,
    source_id AS case_sourceid,
    status AS case_status,
    sub_category_c AS case_sub_category,
    sub_manager_c AS case_sub_manager,
    sub_sub_category_c AS case_sub_sub_category,
    subscription_c AS case_subscription,
    transaction_jurisdiction_c AS case_transaction_jurisdiction,
    transaction_type_c AS case_transaction_type,
    type AS case_type,
    urgency_c AS case_urgency,
    work_around_available_c AS case_work_around_available,
    workspace_id_c AS case_workspace_id
                
    from base
)

select *
from final